[package]
name = "json_parser_from_file"
version = "0.1.0"
authors = ["Paul Montero <lpaulmp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.117"
serde_derive = "1.0"
serde_json = "1.0.59"